name: Python Components

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'lexicon/**'
      - 'genesis/tools/**/*.py'
  pull_request:
    paths:
      - 'lexicon/**'
      - 'genesis/tools/**/*.py'
  workflow_dispatch:

jobs:
  test:
    name: Test Python Components
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies and run tests for Lexicon
        run: |
          cd lexicon/tools
          if [ ! -f "requirements.txt" ]; then
            echo "pytest==7.3.1" > requirements.txt
          fi
          uv pip install -r requirements.txt
          if [ -d "tests" ] || [ -d "src/tests" ]; then
            python -m pytest || echo "Warning: Some Lexicon tests failed"
          else
            echo "No test directory found for Lexicon, skipping tests"
          fi
      
      - name: Install dependencies and run tests for Genesis tools
        run: |
          cd genesis/tools/embedding
          if [ -f "pyproject.toml" ]; then
            uv pip install -e . || echo "Warning: Install failed, installing minimal requirements"
            if [ "$?" -ne "0" ]; then
              pip install pytest
            fi
          else
            pip install pytest
          fi
          if [ -d "tests" ] || grep -r "def test_" .; then
            python -m pytest || echo "Warning: Some Genesis tools tests failed"
          else
            echo "No tests found for Genesis tools, skipping tests"
          fi
  
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install linting tools
        run: pip install black flake8 mypy
      
      - name: Run black
        continue-on-error: true
        run: |
          if [ -d "lexicon/tools/src" ]; then
            black --check lexicon/tools/src || echo "Warning: Formatting issues found in Lexicon"
          fi
          if [ -d "genesis/tools/embedding" ]; then
            black --check genesis/tools/embedding || echo "Warning: Formatting issues found in Genesis tools"
          fi
      
      - name: Run flake8
        continue-on-error: true
        run: |
          if [ -d "lexicon/tools/src" ]; then
            flake8 lexicon/tools/src || echo "Warning: Linting issues found in Lexicon"
          fi
          if [ -d "genesis/tools/embedding" ]; then
            flake8 genesis/tools/embedding || echo "Warning: Linting issues found in Genesis tools"
          fi
      
      - name: Run mypy
        continue-on-error: true
        run: |
          if [ -d "lexicon/tools/src" ]; then
            mypy lexicon/tools/src || echo "Warning: Type checking issues found in Lexicon"
          fi
          if [ -d "genesis/tools/embedding" ]; then
            mypy genesis/tools/embedding || echo "Warning: Type checking issues found in Genesis tools"
          fi