INSERT INTO "website" (
    id,
    description,
    user_id, -- replace with an actual user ID from your database
    domain,
    verified_at,
    tags,
    category,
    upvotes,
    downvotes,
    total_views,
    is_verified,
    status,
    is_featured,
    created_at,
    updated_at
) VALUES 
    (
        gen_random_uuid(),
        'A minimalist portfolio showcasing creative work and projects',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://minimal.studio',
        NOW(),
        '["design", "portfolio", "minimalist"]',
        'portfolio',
        124,
        12,
        1500,
        true,
        'public',
        true,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Daily updates on tech trends and software development',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://techbytes.dev',
        NOW(),
        '["technology", "programming", "news"]',
        'blog',
        89,
        5,
        800,
        true,
        'public',
        false,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Curated collection of indie games and developer stories',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://indiegame.world',
        NOW(),
        '["games", "indie", "development"]',
        'community',
        256,
        18,
        2300,
        true,
        'public',
        true,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Handcrafted jewelry and artistic accessories',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://artisan.shop',
        NOW(),
        '["jewelry", "handmade", "shop"]',
        'ecommerce',
        45,
        3,
        600,
        true,
        'public',
        false,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Personal thoughts on life, travel, and adventure',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://wanderlust.blog',
        NOW(),
        '["travel", "lifestyle", "photography"]',
        'blog',
        167,
        21,
        1200,
        true,
        'public',
        false,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Open source project documentation and guides',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://docs.openlib.dev',
        NOW(),
        '["documentation", "open-source", "guides"]',
        'docs',
        78,
        4,
        950,
        true,
        'public',
        false,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Upcoming indie game with pixel art style',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://pixelquest.game',
        NULL,
        '["game", "pixel-art", "indie"]',
        'fun',
        0,
        0,
        0,
        false,
        'pending',
        false,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Agency specializing in brand identity and web design',
        'HnOIPYkdfdM6Lnsfd7ft7wW2QzwMSSQ3',
        'https://creative.agency',
        NULL,
        '["design", "branding", "agency"]',
        'business',
        0,
        0,
        0,
        true,
        'unlisted',
        false,
        NOW(),
        NOW()
    );
